### ISSUE TITLE
Add netstandard 2.0 support

### ISSUE THREAD

**Issue by mitchdowd** [seesharper/LightInject#429]
Currently the LightInject.cs file does not compile in a netstandard2.0 project.  Current compilation error is as follows:

* error CS0246: The type or namespace name 'LocalBuilder' could not be found (are you missing a using directive or an assembly reference?)

What I am currently doing to work around that and allow it to compile is to `#define NETSTANDARD1_6` at the top of the file.

It would be great for the conditional compilations within the file to support netstandard 2.0+ out of the box without modification so they don't break during upgrades.

**Comment by seesharper** [comment]
Yeah, I know. This one is long overdue. Looking into it 👍

**Comment by seesharper** [comment]
Trying to decide if we actually need those older netstandard versions. It would be so much easier just to target netstandard2.0 and be done with it

**Comment by seesharper** [comment]
Microsoft is pushing really hard for library developers to move to netstandard2.0 mainly because of the simplified dependency resolution that brings. Still, we have a history of not breaking stuff for people and setting the line at netstandard2.0 might, although not likely , break for someone. That is what you get when maintaining a library over several years :) I think we will end up just adding netstandard2.0 support and keep the others at least for a while. Maybe we do a clean cut at the next major.

**Comment by seesharper** [comment]
Closed by #439
